---
- MiqReport:
    title: VMware Virtual machines resource reallocation
    rpt_group: Custom
    rpt_type: Custom
    priority: 
    db: EmsEvent
    cols:
    - event_type
    - created_on
    include:
      vm:
        columns:
        - name
        - description
        - created_on
    col_order:
    - vm.name
    - vm.description
    - vm.created_on
    - event_type
    - created_on
    headers:
    - VM and Instance Name
    - VM and Instance Description
    - VM and Instance Date Created
    - Event Type
    - Date Created
    conditions: !ruby/object:MiqExpression
      exp:
        "=":
          field: EmsEvent-event_type
          value: ReconfigVM_Task_Complete
      context_type: 
    order: Ascending
    sortby:
    - created_on
    - vm.description
    group: 
    graph: 
    dims: 
    filename: 
    file_mtime: 
    categories: []
    timeline: 
    template_type: report
    where_clause: 
    db_options: {}
    generate_cols: 
    generate_rows: 
    col_formats:
    - 
    - 
    - 
    - 
    - 
    tz: 
    time_profile_id: 
    display_filter: 
    col_options: {}
    rpt_options:
      :pdf:
        :page_size: US-Letter
      :queue_timeout: 
    miq_group_id: 20000000000021
    user_id: 20000000000002
    menu_name: Virtual Machine Reconfigure
